services:
<<<<<<< HEAD
    antispam:
        class: AppBundle\Antispam\Antispam
        arguments: ['%antispam_length%', '@mailer']
    string.util:
        class: AppBundle\Util\StringUtil
=======
#    app.example:
#        class: AppBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
>>>>>>> 805dbb358a62bf481f729e9424607f02abef414b
